---
name: Lint Code Base
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Check super-linter
        uses: github/super-linter@v4.9.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /